// Builds src/shared/usPlaces.js (US towns/cities with 5,000+ people) from the
// GeoNames dump, for instant location autofill without any network calls.
// Data: GeoNames (https://www.geonames.org), CC BY 4.0.
// Usage: download https://download.geonames.org/export/dump/cities5000.zip,
//        unzip, then: node scripts/build-places.js path/to/cities5000.txt
import fs from 'node:fs';

const rows = fs.readFileSync(process.argv[2], 'utf8').split('\n')
  .map((l) => l.split('\t'))
  .filter((c) => c[8] === 'US' && c[10] && /^[A-Z]{2}$/.test(c[10]))
  .map((c) => ({ name: c[1], st: c[10], lat: Number(c[4]).toFixed(3), lng: Number(c[5]).toFixed(3), pop: Number(c[14]) || 0 }))
  .sort((a, b) => b.pop - a.pop);

// One "Name|ST|lat|lng|population" line per place, biggest first.
const seen = new Set();
const lines = rows.filter((r) => !seen.has(`${r.name}|${r.st}`) && seen.add(`${r.name}|${r.st}`))
  .map((r) => [r.name.replace(/\|/g, ' '), r.st, r.lat, r.lng, r.pop].join('|'));
const out = `// Generated by scripts/build-places.js. US places with 5,000+ people.
// Data: GeoNames (https://www.geonames.org), licensed CC BY 4.0.
export const US_PLACES = ${JSON.stringify(lines.join('\n'))};
`;
fs.writeFileSync(new URL('../src/shared/usPlaces.js', import.meta.url), out);
console.log(`Wrote ${lines.length} places (${Math.round(out.length / 1024)} KB)`);
